module.exports = {
     WEATHERSTACK_ACCESS_KEY: process.env.WEATHERSTACK_ACCESS_KEY,
     MAPBOX_ACCESS_KEY: process.env.MAPBOX_ACCESS_KEY,
     POSITIONSTACK_ACCESS_KEY: process.env.POSITIONSTACK_ACCESS_KEY
}